### ISSUE TITLE
MacOS users, here is something maybe helpful.

### ISSUE THREAD

**Issue by LarrysGIT** [blawar/nut#220]
You git clone the repo and execute `python3 nut_gui.py`, a lot of missing modules, you install one after another, until you get an error following,

```
    edgeToken = EdgeToken(cdn.clientIds['tagaya'])
TypeError: 'NoneType' object is not subscriptable
```

So, here is the workaround, check out this commit `62ce7cd78ecf09951613638935c48da2c6cc717a`, you will find the histories of `conf/nut.default.conf` file with the following content missing from the release. Simply copy the following `cdn` block into `conf/nut.default.conf`, this should solve the error.

```
    "cdn": {
        "region": "US",
        "firmware": "10.2.0-1.0",
        "environment": "lp1",
        "calibration": "PRODINFO.bin",
        "clientIds": {
            "eShop": "93af0acb26258de9",
            "atumC1": "3117b250cab38f45",
            "tigers": "d5b6cac2c1514c56",
            "tagaya": "41f4a6491028e3c4"
        },
        "dAuth": {
            "keyGeneration": 11,
            "userAgent": "libcurl (nnDauth; 16f4553f-9eee-4e39-9b61-59bc7c99b7c8; SDK 10.4.0.0)",
            "sysDigest": "CusHY#000a0200#90k0dE_eO7hRcs6ByTZMvgUm4lhEoqAlik96WkznQcQ="
        }
    },
```

And continually, you likely need to install other missing modules, most of them just install via `pip3 install module`, there is one `No module named 'Crypto'`, run the following code to install it.

```
pip3 install pycryptodome==3.4.3
```

**Comment by introkun** [comment]
Fixed in #219

**Comment by switch64** [comment]
#219 may have fixed the first problem, but I received the `No module named 'Crypto'` error, and running `pip3 install pycryptodome==3.4.3` does not seem to help.

**Comment by dbw-holic** [comment]
> #219 may have fixed the first problem, but I received the `No module named 'Crypto'` error, and running `pip3 install pycryptodome==3.4.3` does not seem to help, as well as installing the latest version.

@switch64 I have the same problem, tried the workaround above-mentioned but to no avail. At the moment, Nut is unavailable for my macOS. Did you resolve this problem by any chance?

**Comment by codingwiththiago** [comment]
Same problem for me, and running `pip3 install pycryptodome==3.4.3` did not solve it :/
